### ISSUE TITLE
SS drop on chat message

### ISSUE THREAD

**Issue by Blaylock1988** [Bishbash777/SEDB-RELOADED#6]
Still experiencing 0.10 to 0.15 SS drop on nearly vacant server for every single SE chat message. This occurs only for SE -> Discord, and not the opposite. Symptoms do not occur with Player Join/Connect/Disconnect messages. This problem does not occur with Rexxar's Torch Discord plugin, however we need the expanded features of SEDB. 

Video showing issue here: https://imgur.com/a/diQTgLs

**Comment by protectedsnow** [comment]
i think this is solved by last major update. can be closed.

**Comment by Blaylock1988** [comment]
yeah this seems to have gone away with the last major update that brought the new GUI

**Comment by kontu** [comment]
Just to report since you reverted things; this came back :(  We finally have it on a couple of our new instances we just spun up recently; but not on others running on the exact same box

**Comment by Blaylock1988** [comment]
Yep. Problem is back with the revert for Guardians Vanilla too. :'(

**Comment by protectedsnow** [comment]
when did the problem appear?  after update?

**Comment by kontu** [comment]
The problem existed in v1.x; was gone in v2.0.2.2->2.0.2.4; back in v2.0.2.5. Been brought up by people in the torch discord since at least SE v195

**Comment by protectedsnow** [comment]
maybe bish broke something in my fixes 
you can use 2.0.2.4, but in this version death logs not working properly

**Comment by Bishbash777** [comment]
Fixed in previous updates
